# null values in iterator functions testing

@baseURL = http://localhost:8080/v1






###

# null values in iterator functions 
# countItems, sumItems, anyItems, allItems
POST {{baseURL}}/rules/evaluate

{
    "data": [
        {
            "type": "rule",
            "attributes": {
                "expression": "countItems(@this.that, \"boo\") > 0 or sumItems(@this.that, \"boo\", 2) > 2"
            }
        },
        {
            "type": "evaluationData",
            "attributes": {
                "this": {
                    "that": null
                }
            }
        }
    ]
}