@hostname = localhost
@port = 8080


###
GET http://{{hostname}}:{{port}}/v1/rules?sortColumnName=name&sortDirection=ASC&page=1&pageSize=10&searchColumnName=Code&searchValue=bug


###
GET http://{{hostname}}:{{port}}/v1/guidelines?sortColumnName=Name&sortDirection=ASC&page=1&pageSize=10&searchColumnName=Name&searchValue=4


###
GET http://{{hostname}}:{{port}}/v1/eav?sortColumnName=Entity&sortDirection=ASC&page=1&pageSize=10&searchColumnName=Attribute


###
POST http://{{hostname}}:{{port}}/v1/guidelines/evaluateall

{
  "data": [
    {
      "type": "evaluationData",
      "attributes": {
        "validationPoint": "timeEntry",
        "timeEntry": {
          "workHours": 0,
          "workDate": "2022-07-11T17:50:16.279Z",
          "codes": [],
          "workDescription": "whatever",
          "matter": {
            "matterId": "foo",
            "matterNumber": "bar",
            "matterGroup": "lorem",
            "clientNumber": 8888,
            "clientId": 2222,
            "clientGroup": 4444,
            "practiceArea": "",
            "matterLocation": ""
          },
          "created": "2022-07-11T17:50:16.279Z",
          "tkLocation": "",
          "tkTitle": "",
          "tkArea": "",
          "totalFee": 0,
          "billable": false,
          "vacations": false,
          "phantom": false,
          "status": "none",
          "biller": "",
          "billingtimekeeper": ""
        }
      }
    }
  ]
}


### 
POST http://{{hostname}}:{{port}}/v1/rules/evaluate

{
    "data": [
        {
            "type": "evaluationData",
            "attributes": {
                "timeEntry": {
                    "name": "entry1",
                    "transactionDate": "2022-03-05T00:00:00.000Z"
                }
            }
        },
        {
            "type": "rule",
            "attributes": {
                "expression": "dateDiff(days, @timeEntry.transactionDate, today()) > 30"
            }
        }
    ]
}


###
POST http://{{hostname}}:{{port}}/v1/rules/evaluate

{
  "data": [
    {
      "type": "evaluationData",
      "attributes": {
        "invoice": {
          "times": [
            {
              "currency": "USD",
              "end": "2019-01-01T01:00:00Z",
              "billAmount": 11000,
              "quantity": "1"
            },
            {
              "currency": "EU",
              "end": "2019-01-01T02:00:00Z",
              "billAmount": 100,
              "quantity": "2"
            },
            {
              "currency": "USD",
              "end": "2019-01-01T03:00:00Z",
              "billAmount": 3333333,
              "quantity": "3"
            }
          ]
        }
      }
    },
    {
      "type": "rule",
      "attributes": {
        "expression": "sumItems(@invoice.times, @row.currency like \"%USD%\", @row.billAmount) > 10000"
      }
    }
  ]
}

###
# Delete a non existing guideline.. 
DELETE http://{{hostname}}:{{port}}/v1/guidelines/f5d5afab-227d-417c-91eb-93b70718de8b
